mode: train
nepoch: 3000
seed: 20

defaults:
  - hydra: default
  - defaults/data@_here_
  - model: eac
  - defaults/run@_here_
  - defaults/record@_here_
  - defaults/loss@_here_
  - _self_

data:
  atom_rcut: 4.0
  probe_rcut: 6.0
  train:
    paths: null
    frame_size: 1
    probe_size: 5
    num_workers: 0
    epoch_size: 10
  valid:
    paths: null
    frame_size: 1
    probe_size: 5
    num_workers: 0
    epoch_size: 5
  test: null
